from pydantic import BaseModel, Field, field_validator
from typing import Optional, Literal, Dict, Any
from datetime import datetime
from app.utils.evm_addresses import is_valid_address
from app.utils.amounts import parse_usdc_to_atomic, validate_decimal_precision, AmountError


class TransactionIntentCreate(BaseModel):
    client_request_id: str = Field(..., description="Idempotency key generated by client")
    recipient_wallet: str = Field(..., description="Recipient EVM wallet address")
    amount: str = Field(..., description="Amount in USDC (e.g., '25.50')")
    purpose: Optional[str] = Field(default=None, description="Purpose of transfer")
    selected_sender_wallet: str = Field(..., description="User's linked wallet to send from")
    risk_disclosure_version: str = Field(default="v1.0", description="Version of risk disclosure acknowledged")
    
    @field_validator("recipient_wallet", "selected_sender_wallet")
    @classmethod
    def validate_address(cls, v: str) -> str:
        if not is_valid_address(v):
            raise ValueError("Invalid Ethereum address format")
        return v.lower()
    
    @field_validator("amount")
    @classmethod
    def validate_amount(cls, v: str) -> str:
        validate_decimal_precision(v)
        try:
            atomic = parse_usdc_to_atomic(v)
            if atomic <= 0:
                raise AmountError("Amount must be positive")
        except AmountError as e:
            raise ValueError(str(e))
        return v


class TransactionIntentSubmit(BaseModel):
    transaction_hash: str = Field(..., description="Transaction hash from wallet")
    
    @field_validator("transaction_hash")
    @classmethod
    def validate_hash(cls, v: str) -> str:
        v = v.strip()
        if not v.startswith("0x"):
            raise ValueError("Transaction hash must start with 0x")
        if len(v) != 66:
            raise ValueError("Transaction hash must be 32 bytes (66 chars with 0x)")
        try:
            int(v, 16)
        except ValueError:
            raise ValueError("Transaction hash must be valid hex")
        return v.lower()


class TransactionIntentCancel(BaseModel):
    pass


class TransactionIntentResponse(BaseModel):
    id: str
    user_id: str
    client_request_id: str
    sender_wallet: str
    recipient_wallet: str
    amount_atomic: str
    amount_display: str
    token_symbol: str
    token_contract: str
    token_decimals: int
    chain_id: int
    status: Literal[
        "PENDING_SIGNATURE",
        "SUBMITTED",
        "CONFIRMING",
        "CONFIRMED",
        "FAILED",
        "EXCEPTION_MISMATCH",
        "EXPIRED",
        "CANCELLED_BEFORE_SUBMISSION",
    ]
    risk_disclosure_version: str
    risk_disclosure_accepted_at: Optional[str]
    policy_result: Optional[Dict[str, Any]]
    created_at: datetime
    submitted_at: Optional[datetime]
    confirmed_at: Optional[datetime]
    expires_at: datetime
    transaction_hash: Optional[str]
    failure_code: Optional[str]
    failure_reason: Optional[str]
    metadata: Dict[str, Any]


class TransactionIntentListResponse(BaseModel):
    intents: list[TransactionIntentResponse]
    total: int


class ChainConfigResponse(BaseModel):
    chain_id: int
    rpc_url: str
    explorer_url: str
    usdc_address: str
    usdc_decimals: int
    usdc_symbol: str


class BalanceResponse(BaseModel):
    wallet: str
    balance_atomic: str
    balance_display: str
    token_symbol: str
    token_contract: str
    token_decimals: int
    chain_id: int
    timestamp: datetime